[[constraint]]
  branch = "master"
  name = "github.com/eidolon/wordwrap"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[prune]
  go-tests = true
  unused-packages = true
